name: MATLAB Build
on:
  push:
jobs:
  package-toolbox:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup mex
        uses: matlab-actions/run-command@v2
        with:
          command: mex -setup
      - name: Run MATLAB Build
        uses: matlab-actions/run-build@v2
        with:
          tasks: clean build
      - name: Upload toolbox
        uses: actions/upload-artifact@v4
        with:
          name: Toolbox
          path: |
            PortalToolbox.mltbx
  integration-tests:
    needs: package-toolbox
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Download toolbox 
        uses: actions/download-artifact@v4
        with:   
          name: Toolbox
      - name: Install toolbox
        uses: matlab-actions/run-command@v2
        with:
          command: matlab.addons.install("PortalToolbox.mltbx")
      - name: Run Tests
        uses: matlab-actions/run-command@v2
        with:
          command: portal.getCake
